<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Gmod Lua Syntax [2021 Edition]</string>

	<!-- File extentions -->
	<key>fileTypes</key>
	<array>
		<string>lua</string>
	</array>

	<!-- code folding -->
	<key>foldingStartMarker</key>
	<string>^\s*\b(function|local\s+function|if|for)\b|{[ \t]*$|\[\[</string>

	<key>foldingStopMarker</key>
	<string>\bend\b|^\s*}|\]\]</string>

	<!-- shortcut key -->
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Gmod Lua</string>

	<key>patterns</key>
	<array>
		<!-- function headers -->
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.scope.lua</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lua</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.lua</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.lua</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(function)\s+([a-zA-Z_.:0-9]+[.:])?([a-zA-Z_]\w*)\s*(\()([^)]*)(\))</string>
			<key>name</key>
			<string>meta.function.lua</string>
		</dict>
		<!-- Anonymous functions -->
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.lua</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.lua</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(function)\s*(\()([^)]*)(\))</string>
			<key>name</key>
			<string>meta.function.lua</string>
		</dict>
		<!-- Illegal comments -->
		<dict>
			<key>match</key>
			<string>\*/.*\n</string>
			<key>name</key>
			<string>invalid.illegal.stray-comment-end.lua</string>
		</dict>
		<!-- hexadecemal/decimal constants -->
		<dict>
			<key>match</key>
			<string>\b0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.lua</string>
		</dict>
		<!-- Single quoted strings -->
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
			</array>
		</dict>
		<!-- Double quoted strings -->
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
			</array>
		</dict>
		<!-- Multiline strings -->
		<dict>
			<key>begin</key>
			<string>(?&lt;!--)\[(=*)\[</string> <!-- negative lookbehind to not match multiline comments -->
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.other.multiline.lua</string>
		</dict>
		<!-- Multiline comments (pure Lua) -->
		<dict>
			<key>begin</key>
			<string>--\[(=*)\[</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>name</key>
			<string>comment.block.lua</string>
		</dict>
		<!-- Multiline comments (Garry's Lua) -->
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.lua</string>
		</dict>
		<!-- Single line comment (pure Lua) -->
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(--)(?!\[\[).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-dash.lua</string>
		</dict>
		<!-- Single line comment (Garry's Lua) -->
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//)(?!\[\[).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.lua</string>
		</dict>
		<!-- Control keywords -->
		<dict>
			<key>match</key>
			<string>\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|function|local|in|continue|goto)\b</string>
			<key>name</key>
			<string>keyword.control.lua</string>
		</dict>
		<!-- Important constants -->
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(NULL|false|nil|true|_G|_R|_VERSION|self|math\.(pi|huge))\b|(?&lt;![.])\.{3}(?!\.)</string>
			<key>name</key>
			<string>constant.language.lua</string>
		</dict>
		<!-- Enumerations -->
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(%_ENUMS_%)\b|(?&lt;![.])\.{3}(?!\.)</string>
			<key>name</key>
			<string>constant.language.lua</string>
		</dict>
		<!-- Library functions -->
		<dict>
			<key>match</key>
			<string>\b(%_LIBRARY_FUNCTIONS_%)\b</string>
			<key>name</key>
			<string>support.function.library.lua</string>
		</dict>
		<!-- Global functions -->
		<dict>
			<key>match</key>
			<string>\b(%_GLOBAL_FUNCTIONS_%)\b(?=[(\s{])</string>
			<key>name</key>
			<string>support.function.library.lua</string>
		</dict>
		<!-- Meta functions -->
		<dict>
			<key>match</key>
			<string>(?&lt;=\.|:)\b(%_META_FUNCTIONS_%)\b(?=[(\s{])</string>
			<key>name</key>
			<string>support.function.library.lua</string>
		</dict>
		<!-- Hooks -->
		<dict>
			<key>match</key>
			<string>(%_HOOKS_%)\b(?=[(\s{])</string>
			<key>name</key>
			<string>support.function.library.lua</string>
		</dict>
		<!-- Packages and Derma constants -->
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b%_PACKAGES_AND_DERMA_%\b|(?&lt;![.])\.{3}(?!\.)</string>
			<key>name</key>
			<string>constant.language.lua</string>
		</dict>
		<!-- important constants -->
		<dict>
			<key>match</key>
			<string>\b(CLIENT|SERVER|GAMEMODE|EFFECT|GM|SWEP|TOOL|ENT)\b</string>
			<key>name</key>
			<string>constant.language.lua</string>
		</dict>
		<!-- Operators -->
		<dict>
			<key>match</key>
			<string>\b(and|or|not)\b|\|\||&amp;&amp;|&amp;|\||\+|-|%|#|,|\{|\}|\[|\]|\*|\/|\^|==?|~=|!=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.)</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lua</string>
	<key>uuid</key>
	<string>935EB70E-D44A-48ED-B15E-F155F3AA8360</string>
</dict>
</plist>